# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Talks"
  url = "#projects"
  weight = 30

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# [[main_right]]
#   identifier = "CV"
#   name = "CV"
# #  pre = "<i class='ai ai-cv med-icon'></i>"
#   url = "files/cv.pdf"
#   weight = 1
#   post = "Download my CV"
