# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 2

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 3

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 6

[[main_right]]
   name = "CV"
   #pre = "<i class='ai ai-cv med-icon'></i>"
   url = "files/cv.pdf"
   weight = 7
