# This is a basic workflow to help you get started with Actions

name: Build site and deploy to S3 bucket

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    # Sets up Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.74.3'
        extended: true

    # Builds cjsolsen.com repo
    - name: Build Hugo
      run: hugo --minify
      env:
        HUGO_PARAMS_MAP: '{"engine":"1","api_key":"${{ secrets.GMAPS }}","zoom":"15"}'
  
    # Deploys built website to S3
    - name: Deploy to S3
      run: hugo deploy --force --maxDeletes -1 --invalidateCDN
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PASS }}
